### ISSUE TITLE
UI-less mode

### ISSUE THREAD

**Issue by unfa** [jpcima/spectral#2]
I'd love a way to hide the UI elements. Possibly with a hotkey? Or something like double-click?

What do you think?

**Comment by jpcima** [comment]
>What do you think?

Agreed. The intention was to show elements only when the mouse is over the window, however the DISTRHO plugin framework lacks support functionality.
So that will be a prerequisite, unless that I choose a different way to tackle the problem.

**Comment by jpcima** [comment]
Made in 5f17aff a button which hides the UI.
A left click on screen makes it reappear.
